Add e2e test report to CI

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -131,6 +131,12 @@ jobs:
       run: |
         set -e
         make e2e-log-operator KUBE_VERSION=$KUBE_VERSION
+    - name: Upload test results
+      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      with:
+        path: .testresults/e2e/*.xml
+        name: e2e-junit-${{ matrix.group }}-${{ matrix.kube-version }}
+        retention-days: 7
 
   e2e-tests-check:
     runs-on: ubuntu-latest
@@ -148,3 +154,16 @@ jobs:
             echo "One or more matrix jobs failed."
             false
           fi
+      - name: Collect test results
+        if: always()
+        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+        with:
+          merge-multiple: true
+          pattern: e2e-junit-*
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@65fe03598d8d251738592a497a9e8547a5c48eaa # v5.6.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '.testresults/e2e/*.xml'
+          comment: true
+          skip_annotations: true
